### ISSUE TITLE
Reduce products opacity when they don't have shipping availability to your location

### ISSUE THREAD

**Issue by sosahcarlos** [sdelquin/sendhereplz#22]
As a user I would prefer that the highlight products are the ones that I can buy.
What do you think?

![ezgif-6-9c810515f761](https://user-images.githubusercontent.com/4333825/90991427-e9e74f80-e5a0-11ea-9f80-0d9d214742c7.gif)

**Comment by Pustur** [comment]
Yeah from your gif this could work well. Drop the opacity for the products that are not eligible, but allow to hover over them to see them clearly. 👍 

I wonder if it's better to still have a different color for the title or something else to recognize the non-eligible items?  
I imagine that maybe as you're scrolling through the list your cursor could get in the way and it would look like the item under it is available when it's not. Not sure if you get what I mean...

**Comment by sosahcarlos** [comment]
That's a good point. Something like that?

![title-red](https://user-images.githubusercontent.com/4333825/90994042-35a0f580-e5af-11ea-9f83-ab43cb464b27.gif)

**Comment by Pustur** [comment]
I tried the code from your `reduce-opacity-to-non-deliverable-products` branch and the problem I was describing doesn't really happen when scrolling normally. However it could happen when changing the page and the mouse is already over an item that ends up being not eligible. When the check finishes the user doesn't see any change but that item is in fact not eligible.

In my opinion we could just keep the ~striketrough~ style in addition to the opacity to solve this potential problem.

**Comment by sosahcarlos** [comment]
I have been talking about it with @sdelquin and we think it would be better if the user wants to see something he can see it clearly.
Instead of crossing out the name of the product, we are testing adding an icon (ignore alignment):
![ezgif-2-42724b3775c5](https://user-images.githubusercontent.com/4333825/91075395-e651d800-e635-11ea-8239-a8293b970b5c.gif)

Does it make sense to you?

**Comment by Pustur** [comment]
Yes that's even better than my idea
