### ISSUE TITLE
Don't work with some items

### ISSUE THREAD

**Issue by Sacrar** [sdelquin/sendhereplz#31]
The extension does not work with some products. Maybe those products that have the "subscribe and save" option. Attached is a capture of melatonin products. The extension marks the first two products as available. When you mark the "one-time purchase" option, the message not sending will appear.

<a href='https://postimg.cc/bSX2SgJV' target='_blank'><img src='https://i.postimg.cc/bSX2SgJV/Anotaci-n-2020-09-02-181908.png' border='0' alt='Anotaci-n-2020-09-02-181908'/></a>

<a href='https://postimg.cc/Jt4bJ6Pv' target='_blank'><img src='https://i.postimg.cc/Jt4bJ6Pv/Anotaci-n-2020-09-02-183536.png' border='0' alt='Anotaci-n-2020-09-02-183536'/></a>

<a href='https://postimg.cc/K1mB505d' target='_blank'><img src='https://i.postimg.cc/K1mB505d/Anotaci-n-2020-09-02-181619.png' border='0' alt='Anotaci-n-2020-09-02-181619'/></a>

Link for check it:
https://www.amazon.es/s?k=melatonina&__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&ref=nb_sb_noss_2

**Comment by sosahcarlos** [comment]
Good catch! In this case the product can shipped through at least one of the available purchase options, therefore displaying this item as non-deliverable would not be accurate. 

However, marking the products that can be sent only via "subscribe and save" could be seen as a new feature to be implemented in the future.

Thank you for the feedback! :)

**Comment by Sacrar** [comment]
> 
> 
> Good catch! In this case the product can shipped through at least one of the available purchase options, therefore displaying this item as non-deliverable would not be accurate.
> 
> However, marking the products that can be sent only via "subscribe and save" could be seen as a new feature to be implemented in the future.
> 
> Thank you for the feedback! :)

No, the product cannot be shipped by any of the options. Once you click the "configure now" button to subscribe, the next screen is a "sorry we cannot ship to this address" message.

**Comment by sosahcarlos** [comment]
Oh now I see what you mean. We'll get on it and see what we can do about it.

**Comment by uptoeleven** [comment]
The problem is that static content sent in the first request doesn't contain any "error" type elements with `.a-color-error`,
so there isn't anything to detect.

**Comment by sdelquin** [comment]
This issue will be closed due to inactivity
