### ISSUE TITLE
No funciona.

### ISSUE THREAD

**Issue by GPB-X78H-S1** [sdelquin/sendhereplz#40]
Ya no funciona ni en chrome ni en firefox.

**Comment by sdelquin** [comment]
Hola,

Hemos probado y funciona correctamente. ¿Nos puedes indicar algún ejemplo de búsqueda en el que te esté fallando?

Saludos.

**Comment by GPB-X78H-S1** [comment]
Buenos días.
He probado a buscar un cable de sata a usb que ya sabía que no enviaban a Canarias y no me filtra ninguno. Se ve un ícono de carga en cada producto, pero luego siguen saliendo todos. Luego probé a buscar diversas cosas como televisores, ordenadores, etc. Pero sigue cargándolos todos. Lo que sí hace es señarte el precio distinto, pero no marca en gris los que no tienen envío. Probé en firefox y pasa lo mismo. Quité Addblocker por si fuera eso y reinicié en ambos navegadores, nada.

**Comment by sdelquin** [comment]
¿Nos puedes enviar una captura de pantalla de toda la página (incluyendo el header) a ver si podemos detectar qué está ocurriendo? Gracias
